name: Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          path: "main"
      - uses: actions/setup-node@v5
        with:
          node-version: "24"
      - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: build
        run: |
          pushd main
          npm install
          export REPO_NAME=${{ env.REPOSITORY_NAME }}
          npm run build
          popd
      - uses: actions/checkout@v5
        with:
          ref: "gh-pages"
          path: "gh-pages"
      - run: cp -r main/out/* gh-pages/
      - name: commit-and-push
        run: |
          pushd gh-pages
          git config user.name yuya-katayama-hal
          git config user.email ths51288@ths.hal.ac.jp
          git add .
          git commit -m "Update"
          git push
          popd
